# Generated by Django 4.2.3 on 2023-07-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=32, verbose_name='Nombre Categoria')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creacion Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=32, verbose_name='Nombre Marca')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creacion Marca')),
            ],
        ),
        migrations.AlterField(
            model_name='contactomensaje',
            name='apellidoMaterno',
            field=models.CharField(max_length=32, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='contactomensaje',
            name='apellidoPaterno',
            field=models.CharField(max_length=32, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='contactomensaje',
            name='comentarios',
            field=models.CharField(max_length=100, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='contactomensaje',
            name='correo',
            field=models.CharField(max_length=32, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='contactomensaje',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre Zapatilla')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('encabezado', models.CharField(max_length=100, verbose_name='Encabezado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('info1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Info1')),
                ('info2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Info2')),
                ('info3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Info3')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='zapatillas', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.marca')),
            ],
        ),
    ]
