# Generated by Django 4.2.3 on 2023-07-06 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_categoria_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creacion Zapatilla'),
            preserve_default=False,
        ),
    ]
